services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=EcdcFlask
      - DB_USERNAME=admin
    expose:
      - 5000
    volumes:
      - pgdb1:/app/db

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80" 
volumes:
  pgdb1:
