services:
  flask:
    build: .
    container_name: ecdc-flask
    restart: always
    environment:
      - APP_NAME=EcdcFlask
      - DB_USERNAME=admin
    expose:
      - 5000

  nginx:
    build: ./nginx
    container_name: nginx_serv
    restart: always
    ports:
      -"80:80"
