services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=EcdcFlask
      - DB_USERNAME=admin
    expose:
      - 5000

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "88:88" 
    expose:
      - 88
